version: "3.8"
services:
  kafka1:
    image: suhail50/kafka
    container_name: kafka1
    ports:
    - "8081:8081"
    environment:
      - KAFKA_CLUSTER_ID=TestCluster
    volumes:
    - ./properties/server1.properties:/kafka/config/kraft/server.properties
    - ./data/broker1:/tmp/kafka-logs
  kafka2:
    image: suhail50/kafka
    container_name: kafka2
    ports:
    - "8082:8082"
    environment:
      - KAFKA_CLUSTER_ID=TestCluster
    volumes:
    - ./properties/server2.properties:/kafka/config/kraft/server.properties
    - ./data/broker2:/tmp/kafka-logs     
  kafka3:
    image: suhail50/kafka
    container_name: kafka3
    ports:
    - "8083:8083"
    environment:
      - KAFKA_CLUSTER_ID=TestCluster
    volumes:
    - ./properties/server3.properties:/kafka/config/kraft/server.properties
    - ./data/broker3:/tmp/kafka-logs           